config/routes.rb
Rails.application.routes.draw do

  devise_for :users do 
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'rooms#index'
  resources :users do
  	member do
  		get :following, :followers
  	end
  end
  resources :rooms do
    resources :room_members, only:[:new, :create]
  end
  resources :friends, only:[:create]
  post 'users/search' =>  'users#search', as: :search
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	belongs_to :room
	has_many :reads
	after_create_commit { MessageBroadcastJob.perform_later (self) }
	validates :content, presence: true
	validates :user_id, presence: true
	validates :room_id, presence: true
end

app/models/read.rb
class Read < ApplicationRecord
  belongs_to :message
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :messages, dependent: :destroy
	has_many :room_members
	has_many :users, through: :room_members
end

app/models/room_member.rb
class RoomMember < ApplicationRecord
	belongs_to :room
	belongs_to :user
	validates :room_id, presence: true
	validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :active_friends, class_name: "Friend",
  					foreign_key: "follower_id",
  					dependent: :destroy
  has_many :passive_friends, class_name: "Friend",
  					foreign_key: "followed_id",
  					dependent: :destroy
  has_many :following, through: :active_friends, source: :followed
  has_many :followers, through: :passive_friends, source: :follower
  has_many :messages
  has_many :room_members
  has_many :rooms, through: :room_members
  mount_uploader :picture, ::PictureUploader
  validates :name, presence: true


  def follow(other_user)
  	active_friends.create(followed_id: other_user.id)
  end

  def following?(other_user)
  	following.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  	def configure_permitted_parameters
    	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :picture])
    	devise_parameter_sanitizer.permit(:account_update, keys: [:name, :line_id])
  	end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	def create
		#友達になる機能
		user = User.find(params[:followed_id])
		current_user.follow(user)
		redirect_to user
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/room_members_controller.rb
class RoomMembersController < ApplicationController
	def new
		@room = Room.find(params[:room_id])
		@room_member = RoomMember.new
	end

	def create
		@room = Room.find(params[:room_id])
		params[:room_member][:user_id].each do |param|
			if param.to_i > 0
				@room.room_members.where(user_id: param.to_i).first_or_create
			end
		end
    redirect_to root_path
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
  	@room = Room.find(params[:id]) 
    if @room.users.find_by(id: current_user.id) == nil
      redirect_to root_path, notice: "招待されなければ入室できません。"
    end
  	@message = Message.new
  end

  def index
    @rooms = current_user.rooms
  end

  def create
    #roomに所属しているuserがcurrent_userとusers/showで開かれているuserの2人だけのとき、新しいroomを作らず既存のルームにリダイレクトさせる。
    Room.all.each do |room|
      if room.room_members.count == 2
        if room.room_members.find_by(user_id: current_user.id) != nil and room.room_members.find_by(user_id: params[:user_id]) != nil
          redirect_to room_path(room.id) and return
        end
      end
    end
    @room = Room.new
    if @room.save
      @room.room_members.where(user_id: current_user.id).first_or_create
      @room.room_members.where(user_id: params[:user_id]).first_or_create
      redirect_to @room
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if request.referer == nil
      redirect_to users_path, alert: "無効なアクセスです。友達はID検索を用いてお探しください。"
    end
  	@user = User.find(params[:id])
    if @friend = Friend.where(follower_id: current_user.id, followed_id: @user.id).or(Friend.where(follower_id: @user.id, followed_id: current_user.id)).first
    end
  end

  def index
  	@users = current_user.following
    #友人をサーチする
     @q = current_user.following.ransack(params[:q])
     @users = @q.result(distinct: true)
  end

  def edit
  	@user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to edit_user_path(@user.id), notice: "変更が保存されました。"
    else
      render :action => "edit" 
    end
  end

  def search
    user = User.where(line_id: params[:line_id]).first
    if user != nil
      redirect_to user_path(user.id)
    else
      redirect_to users_path, notice: "入力したIDのユーザーは存在しません。"
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :line_id, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/room_members_helper.rb
module RoomMembersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/search.html.erb
<div>
  <%= search_form_for @q, url: user_path(@user.id) do |f| %>

    <%= f.label :line_id_cont %>
    <%= f.search_field :line_id_cont %>

    <%= f.submit %>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= current_user.name %>　としてログインしています。
      <%= link_to "ログアウト", destroy_user_session_path, :method => :delete %>
      <%= link_to "プロフィール編集", edit_user_path(current_user) %>
    <% else %>
      <%= link_to "サインアップ", new_user_registration_path %>
      <%= link_to "ログイン", new_user_session_path %>
    <% end %><br>
    <%= link_to "友達", users_path, {:class=>"glyphicon glyphicon-user"}%>
    <%= link_to "トークルーム", rooms_path, {:class=>"glyphicon glyphicon-comment"} %>
    <%= yield %>

  </body>
</html>

app/views/messages/_current_user_message.html.erb
<figure class="kaiwa-img-right">
	<% if message.user.picture? %>
		<%= image_tag message.user.picture.url %>
	<% else %>
		<%= image_tag ("default.gif") %>
	<% end %>
	<figcaption class="kaiwa-img-description">
		<%= message.user.name %>
	</figcaption>
</figure>
<div class="kaiwa-text-left">
	<p class="kaiwa-text" data-read-flg="<%=message.id%>">
		<% if message.reads.count > 0 %>
			既読
		<% end %>
		<%= message.content %>
	</p>
</div><br><br>

app/views/messages/_message.html.erb
<p>
	<strong>
		<%= message.user.name %>:
	</strong>
	<%= message.content %>
</p>

app/views/messages/_message_form.html.erb
<label>Your message</label>:
<input type= "text" class="form-control" id="message-content" data-speaker="<%=current_user.id%>">
<div class="btn btn-primary" id="submit-message">送信</div>

app/views/messages/_other_users_message.html.erb
<figure class="kaiwa-img-left">
	<% if message.user.picture? %>
		<%= image_tag message.user.picture.url %>
	<% else %>
		<%= image_tag ("default.gif") %>
	<% end %>
	<figcaption class="kaiwa-img-description">
		<%= message.user.name %>
	</figcaption>
</figure>
<div class="kaiwa-text-right">
	<p class="kaiwa-text">
		<%= message.content %>
	</p>
</div><br><br>

app/views/room_members/new.html.erb
<%= form_for([@room, @room_member]) do |f| %>
	<%= f.collection_check_boxes(:user_id, current_user.following, :id, :name) %>
	<%= f.submit "招待" %>
<% end %>

app/views/rooms/index.html.erb
<h1>トーク</h1>
<% @rooms.each do |room| %>
	<div class = "list-group">
    <button type="button" class="list-group-item">
    	<%= link_to room_path(room.id) do %>
				<% room.users.each do |user| %>
					<% if user.id != current_user.id%>
						<%= user.name %>
					<% end %>
				<% end %>
			<% end %>
		</button>	
  </div>
<% end %>

app/views/rooms/show.html.erb
<h4>
	<% @room.users.where.not(id: current_user.id).each do |user| %>
		<%= user.name + "  "%>
	<% end %>
</h4>

<div class="text-right">
	<%= link_to "招待する", new_room_room_member_path(params[:id]) %>
</div>

  <div class="kaiwa" id="messages" data-room= '<%= @room.id%>' data-user='<%= current_user.id%>'>
  	<% @room.messages.each do |message| %>
  		<% if message.user == current_user %>
  			<%= render partial: 'messages/current_user_message', locals: { message: message} %>
  		<% else %>
  			<%= render partial: 'messages/other_users_message' , locals: { message: message}%>
  		<% end %>
  	<% end %>
  </div>

<%= render partial: 'messages/message_form', locals: {message: @message, room: @room}%>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_friends.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "友達に追加", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h2><%= @user.email %></h2>
<%= image_tag @user.picture.url if @user.picture? %>


<div class="form-group">
  <%= form_for (@user) do |f| %>
  	
  	<div>
      <%= f.label :名前 ,:class => "control-label"%><br>
      <%= f.text_field :name, autofocus: true , :class => "form-control"%>
    </div>

    <div>
      <%= f.label :ID,:class => "control-label"%><br>
      <%= f.text_field :line_id, autofocus: true, :class => "form-control"%>
    </div>

    <div>
      <%= f.label :プロフィール画像,:class => "control-label"%><br>
      <%= f.file_field :picture%>
    </div>

  	<div>
      <%= f.submit "更新", class:"btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<!-- 友達をIDで探す -->
<%= form_tag search_path do %>
  <div class= "form-group">
    <label>LineIDで友達を探す</label>
    <%= text_field_tag :line_id%>
    <%= submit_tag '検索' %>
  </div>
<% end %>

  <!-- 友達から探す -->
<% if @users.count > 0 %>
  <%= search_form_for @q do |f| %>
    <div class= "form-group">
      <%= f.label :友達の名前 %>
      <%= f.search_field :name_cont %>
      <%= f.submit %>
    </div>
  <% end %>
<% else %>
  まずはID検索で友達を追加しよう！
<% end %>

<div>
  <p>
    友達 ( <%= current_user.following.count %> )
  </p>
</div>

<% @users.each do |user| %>
  <div class = "list-group"> 
    <button type="button" class="list-group-item"><%= link_to user.name, user %></button>
  </div>
<% end %>

app/views/users/show.html.erb
<h2>
  <%= @user.name%>
</h2>

<% if current_user.id == @user.id %>
  <p>ここはあなた自身のページです。自分自身を追加することはできません。</p>
<% else %>
  <div>
    <% if current_user.following?(@user) %>
      <%= form_tag rooms_path do  %>
    		<div><%= hidden_field_tag :user_id, @user.id%></div>
        <%= submit_tag "トーク", :class => "btn btn-primary" %>
      <% end %>
    <% else %>
    <%= render 'follow' %>
    <% end %>
  </div>
<% end %>